const $ = (s) => document.querySelector(s);
const out = $('#output');
const input = $('#input');
const status = $('#status');
const tool = document.body.dataset.tool;

function setOutput(value, ok = true) {
  if (out) out.textContent = value;
  if (status) status.textContent = ok ? 'Ready' : 'Check your input';
}
function num(id) { return Number($(id)?.value); }
function validFinite(...values) { return values.every(Number.isFinite); }
function money(v) { return `₹${Number(v).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`; }
function downloadBlob(blob, filename) { const url=URL.createObjectURL(blob), a=document.createElement('a'); a.href=url; a.download=filename; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); }

function percentage(){const a=num('#a'),b=num('#b');if(!validFinite(a,b))return setOutput('Enter both numbers.',false);setOutput(`${b}% of ${a} = ${((a*b)/100).toLocaleString()}`)}
function percentageChange(){const from=num('#from'),to=num('#to');if(!validFinite(from,to)||from===0)return setOutput('Enter valid values. Starting value cannot be zero.',false);const c=(to-from)/Math.abs(from)*100;setOutput(`Change: ${c.toFixed(2)}%\n${c>=0?'Increase':'Decrease'}: ${Math.abs(c).toFixed(2)}%`)}
function wordCounter(){const text=input?.value||'';const words=text.trim()?text.trim().split(/\s+/u).length:0;const chars=[...text].length;const noSpaces=[...text.replace(/\s/gu,'')].length;const sentences=text.split(/[.!?]+/u).filter(s=>s.trim()).length;const paragraphs=text.split(/\n\s*\n/u).filter(s=>s.trim()).length;setOutput(`Words: ${words}\nCharacters: ${chars}\nCharacters (no spaces): ${noSpaces}\nSentences: ${sentences}\nParagraphs: ${paragraphs}`)}
function jsonFormatter(){try{setOutput(JSON.stringify(JSON.parse(input.value),null,2))}catch(e){setOutput(`Invalid JSON: ${e.message}`,false)}}
function base64(){try{if(document.body.dataset.mode==='decode'){const bytes=Uint8Array.from(atob(input.value.trim()),c=>c.charCodeAt(0));setOutput(new TextDecoder().decode(bytes))}else{setOutput(btoa(String.fromCodePoint(...new TextEncoder().encode(input.value))))}}catch(e){setOutput(`Could not process Base64: ${e.message}`,false)}}
function urlCodec(){try{setOutput(document.body.dataset.mode==='decode'?decodeURIComponent(input.value):encodeURIComponent(input.value))}catch(e){setOutput(`Invalid encoded text: ${e.message}`,false)}}
function timestamp(){const raw=input?.value.trim();if(!raw)return setOutput('Enter a Unix timestamp.',false);const n=Number(raw),ms=Math.abs(n)<1e12?n*1000:n,d=new Date(ms);if(Number.isNaN(d.getTime()))return setOutput('Invalid timestamp.',false);setOutput(`UTC: ${d.toISOString()}\nLocal: ${d.toString()}\nUnix seconds: ${Math.floor(ms/1000)}\nUnix milliseconds: ${ms}`)}
function uuid(){if(crypto?.randomUUID)return setOutput(crypto.randomUUID());const b=new Uint8Array(16);crypto.getRandomValues(b);b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');setOutput(`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`)}
function password(){const length=Math.min(128,Math.max(4,Math.floor(num('#length')||20))),upper=$('#upper')?.checked!==false,lower=$('#lower')?.checked!==false,numbers=$('#numbers')?.checked!==false,symbols=$('#symbols')?.checked!==false,pools=`${lower?'abcdefghijklmnopqrstuvwxyz':''}${upper?'ABCDEFGHIJKLMNOPQRSTUVWXYZ':''}${numbers?'0123456789':''}${symbols?'!@#$%^&*()-_=+[]{}:,.?':''}`;if(!pools)return setOutput('Select at least one character set.',false);const r=new Uint32Array(length);crypto.getRandomValues(r);let v='';for(let i=0;i<length;i++)v+=pools[r[i]%pools.length];setOutput(v)}
function ageCalculator(){const raw=$('#date')?.value;if(!raw)return setOutput('Select your date of birth.',false);const birth=new Date(`${raw}T00:00:00`),now=new Date();if(Number.isNaN(birth.getTime())||birth>now)return setOutput('Enter a valid date of birth.',false);let years=now.getFullYear()-birth.getFullYear();const before=now.getMonth()<birth.getMonth()||(now.getMonth()===birth.getMonth()&&now.getDate()<birth.getDate());if(before)years--;const last=new Date(now.getFullYear()-(before?1:0),birth.getMonth(),birth.getDate());setOutput(`Age: ${years} years\nDays since last birthday: ${Math.floor((now-last)/86400000)}`)}
function discount(){const price=num('#price'),pct=num('#discount');if(!(price>=0)||!(pct>=0&&pct<=100))return setOutput('Enter a valid price and discount from 0–100%.',false);const saved=price*pct/100;setOutput(`Original price: ${money(price)}\nDiscount: ${money(saved)}\nFinal price: ${money(price-saved)}`)}
function emi(){const P=num('#principal'),annual=num('#rate'),years=num('#years');if(!(P>0)||!(annual>=0)||!(years>0))return setOutput('Enter a valid loan amount, interest rate and tenure.',false);const r=annual/12/100,n=years*12,monthly=r===0?P/n:P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1),total=monthly*n;setOutput(`Monthly EMI: ${money(monthly)}\nTotal interest: ${money(total-P)}\nTotal repayment: ${money(total)}\nPayments: ${n}`)}
function imageCompressor(){const file=$('#file')?.files[0];if(!file)return setOutput('Choose an image first.',false);const quality=Math.min(1,Math.max(.1,num('#quality')/100||.8)),img=new Image(),reader=new FileReader();reader.onload=()=>{img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;canvas.getContext('2d').drawImage(img,0,0);canvas.toBlob(blob=>{if(!blob)return setOutput('Compression failed.',false);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`compressed-${file.name.replace(/\.[^.]+$/,'')}.jpg`;a.textContent=`Download compressed image (${(blob.size/1024).toFixed(1)} KB)`;out.replaceChildren(a);status.textContent=`${(file.size/1024).toFixed(1)} KB → ${(blob.size/1024).toFixed(1)} KB`;},'image/jpeg',quality)};img.src=reader.result};reader.readAsDataURL(file)}
function jpgToPng(){const file=$('#file')?.files[0];if(!file)return setOutput('Choose a JPG image first.',false);const img=new Image(),r=new FileReader();r.onload=()=>{img.onload=()=>{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);c.toBlob(b=>{if(!b)return setOutput('Conversion failed.',false);downloadBlob(b,`${file.name.replace(/\.[^.]+$/,'')}.png`);setOutput(`Converted ${file.name} → PNG (${(b.size/1024).toFixed(1)} KB)`);},'image/png')};img.src=r.result};r.readAsDataURL(file)}
function imageResizer(){const file=$('#file')?.files[0],width=Math.floor(num('#width')),heightInput=$('#height')?.value;if(!file||!(width>0))return setOutput('Choose an image and enter a valid width.',false);const img=new Image(),r=new FileReader();r.onload=()=>{img.onload=()=>{const ratio=img.naturalHeight/img.naturalWidth,height=heightInput?Math.floor(num('#height')):Math.round(width*ratio);if(!(height>0))return setOutput('Enter a valid height.',false);const c=document.createElement('canvas');c.width=width;c.height=height;c.getContext('2d').drawImage(img,0,0,width,height);c.toBlob(b=>{downloadBlob(b,`resized-${file.name.replace(/\.[^.]+$/,'')}.png`);setOutput(`Resized to ${width} × ${height} pixels.`)},'image/png')};img.src=r.result};r.readAsDataURL(file)}
function csvToJson(){const lines=(input?.value||'').trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)return setOutput('Paste CSV with a header row and at least one data row.',false);const parse=line=>line.split(',').map(s=>s.trim().replace(/^"|"$/g,'')),headers=parse(lines[0]),rows=lines.slice(1).map(line=>{const v=parse(line);return Object.fromEntries(headers.map((h,i)=>[h,v[i]??'']))});setOutput(JSON.stringify(rows,null,2))}
function jsonToCsv(){try{const data=JSON.parse(input.value);if(!Array.isArray(data)||!data.length)throw new Error('JSON must be a non-empty array of objects.');const headers=[...new Set(data.flatMap(o=>Object.keys(o)))],esc=v=>`"${String(v??'').replace(/"/g,'""')}"`,csv=[headers.map(esc).join(','),...data.map(o=>headers.map(h=>esc(o[h])).join(','))].join('\n');setOutput(csv)}catch(e){setOutput(`Invalid JSON: ${e.message}`,false)}}
function caseConverter(){const text=input?.value||'',mode=document.body.dataset.mode||'lower';let result=text;if(mode==='upper')result=text.toUpperCase();else if(mode==='title')result=text.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());else if(mode==='sentence')result=text.toLowerCase().replace(/(^|[.!?]\s+)(\p{L})/gu,(m,p,c)=>p+c.toUpperCase());setOutput(result)}
function duplicateLines(){const lines=(input?.value||'').split(/\r?\n/),seen=new Set(),unique=lines.filter(line=>{const k=line.trim();if(!k||seen.has(k))return false;seen.add(k);return true});setOutput(unique.join('\n'))}
function dateDifference(){const a=new Date(`${$('#start')?.value}T00:00:00`),b=new Date(`${$('#end')?.value}T00:00:00`);if(Number.isNaN(a.getTime())||Number.isNaN(b.getTime()))return setOutput('Select both dates.',false);const days=Math.round((b-a)/86400000);setOutput(`Difference: ${Math.abs(days)} days\nDirection: ${days>=0?'End date is after the start date.':'End date is before the start date.'}`)}
const actions={percentage,'percentage-change':percentageChange,'word-counter':wordCounter,'json-formatter':jsonFormatter,base64,urlCodec,uuid,password,timestamp,'age-calculator':ageCalculator,'discount-calculator':discount,'emi-calculator':emi,'image-compressor':imageCompressor,'image-resizer':imageResizer,'jpg-to-png':jpgToPng,'character-counter':()=>{const text=input?.value||'';setOutput(`Characters: ${[...text].length}\nCharacters (no spaces): ${[...text.replace(/\s/gu,'')].length}`)},,'csv-to-json':csvToJson,'json-to-csv':jsonToCsv,'case-converter':caseConverter,'duplicate-lines':duplicateLines,'date-difference':dateDifference};
if($('#run'))$('#run').addEventListener('click',()=>actions[tool]?.());
if(input&&tool==='word-counter')input.addEventListener('input',wordCounter);
if(input&&['json-formatter','csv-to-json','json-to-csv'].includes(tool))input.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')actions[tool]?.()});
